//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarcBachraty.LocalResource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class forms {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal forms() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarcBachraty.LocalResource.forms", typeof(forms).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} + {1}, type the result here.
        /// </summary>
        public static string additioncaptcha {
            get {
                return ResourceManager.GetString("additioncaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string btnsend {
            get {
                return ResourceManager.GetString("btnsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string comments {
            get {
                return ResourceManager.GetString("comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regarding.
        /// </summary>
        public static string contactreason {
            get {
                return ResourceManager.GetString("contactreason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dojo.
        /// </summary>
        public static string dojo {
            get {
                return ResourceManager.GetString("dojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string firstname {
            get {
                return ResourceManager.GetString("firstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string fullname {
            get {
                return ResourceManager.GetString("fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you {0}.
        /// </summary>
        public static string retcontactheader {
            get {
                return ResourceManager.GetString("retcontactheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I will get back to you as soon as I can.&lt;br/&gt;Best regards/&lt;br/&gt;Marc Bachraty.
        /// </summary>
        public static string retcontactmessage {
            get {
                return ResourceManager.GetString("retcontactmessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish to invite for a seminar.
        /// </summary>
        public static string rsnarrange {
            get {
                return ResourceManager.GetString("rsnarrange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish to buy you book.
        /// </summary>
        public static string rsnbuybook {
            get {
                return ResourceManager.GetString("rsnbuybook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish to get in contact.
        /// </summary>
        public static string rsncontact {
            get {
                return ResourceManager.GetString("rsncontact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have a general question.
        /// </summary>
        public static string rsngeneralquestion {
            get {
                return ResourceManager.GetString("rsngeneralquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string rsnother {
            get {
                return ResourceManager.GetString("rsnother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wish to ask about merchandise.
        /// </summary>
        public static string rsnrequestmerchandise {
            get {
                return ResourceManager.GetString("rsnrequestmerchandise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string website {
            get {
                return ResourceManager.GetString("website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
